sudo: required

language: node

services:
  - docker


install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - docker --version  # document the version travis is using
  - docker build -t aurlaw/aurlaw-aspnet-react .  
  - docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
  - docker tag aurlaw/aurlaw-aspnet-react:latest registry.heroku.com/aurlaw-aspnet-react/web:latest
  - docker push registry.heroku.com/aurlaw-aspnet-react/web:latest



deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

